services:
  axum:
    build:
      context: ./axum
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  echo:
    build:
      context: ./echo
      dockerfile: Dockerfile
    ports:
      - 8888:8888

  flask:
    build:
      context: ./flask
    ports:
      - 5000:5000

  adot-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:v0.21.1
    command: ["--config=/etc/otel-agent-config.yaml"]
    volumes:
      - ./adot-config/collector-config.yaml:/etc/otel-agent-config.yaml
    depends_on:
      - "axum"
      - "echo"
      - "flask"

  prometheus:
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./prometheus-config/prometheus-only-itself.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - 80:9090
    depends_on:
      - "adot-collector"
