receivers:
  prometheus:
    config:
      global:
        scrape_interval: 10s
        scrape_timeout: 10s

      scrape_configs:
        - job_name: axum-app
          static_configs:
            - targets:
                - axum:3000
        - job_name: echo-app
          static_configs:
            - targets:
                - echo:8888
        - job_name: flask-app
          static_configs:
            - targets:
                - flask:5000

exporters:
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

service:
  pipelines:
    metrics:
      receivers:
        - prometheus
      exporters:
        - prometheusremotewrite
